apiVersion: apps/v1
kind: deployment
metadata:
  name: gke-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-test
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
      - name: gke-test
        image: gcr.io/apt-reality-357605/test@sha256:7ff4c4ae8d15c0f83685833f680ecdfc7a030a728126a847bd507bd4558f77cf
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
