apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-test
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
      - name: hello-app
        image: gcr.io/apt-reality-357605/test:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
