apiVersion: v1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: gke-test
        image: gcr.io/apt-reality-357605/test:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m 
          limits:
            cpu: 100m
