apiVersion: v1
kind: deployment
metadata:
  name: gke-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-test
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
      - name: gke-test
        image: nginx
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
