apiVersion: apps/v2
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
      - name: gke-test
        image: gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m gcr.io/google-samples/hello-app:1.0
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: gke-test
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gke-hello-app
